### ISSUE TITLE
TypeScript 2.2 Object and Intersection Types

### ISSUE THREAD

**Issue by matt-gadd** [dojo/compose#118]
TypeScript 2.2 will have Object and Intersection types, https://github.com/Microsoft/TypeScript/pull/13604 which should drastically improve our inference through mixins and this.

We should look to see what improvements this can bring in terms of typing.

The code for this is in master so available under `typescript@next`

**Comment by maier49** [comment]
From what I've gathered, I'm not sure this can be directly leveraged to improve typing in compose. Having classes and interface be able to derive from objects can be handy for certain mixin patterns, but I'm not seeing a way to fit it into compose. The main benefit for compose I can see from these changes is the fact that the `this` type of an intersection is now the intersection but this is more of an indirect benefit to users of the library. For example, a previous iteration of the stores API had something like this
```
interface QueryMixin {
  query(query: Query): this;
}
```
Types like this would work a lot better now because `QueryMixin & Store & ...` would properly return itself from a query.

**Comment by agubler** [comment]
@matt-gadd I think we can close this now after the move to TS2.2?
