### ISSUE TITLE
Custom toString() is skipped by the factory 

### ISSUE THREAD

**Issue by lzhoucs** [dojo/compose#81]
Package Version: `"2.0.0-beta.13"`

**Code**

``` typescript
interface Foo {
    fooProp: string;
    toString(): string;
}
const fooFactory = compose<Foo, any>({
    fooProp: 'A Foo',
    toString: function(this: Foo) {
        return `[this.fooProp]`;
    }
});
const foo = fooFactory();
assert.strictEqual(foo.toString(), '[A Foo]');
```

**Expected behavior:**
The `foo.toString()` in example code above is expected to return `[A Foo]`, which has been the the case until recently #65  is merged. [L107](https://github.com/dojo/compose/pull/65/files#diff-65a32a71a505e06f0e0dfb7da1071c47R107) seems to intentionally skip `toString` that is defined in the prototype and a `toString` defined by the library in [L58](https://github.com/dojo/compose/pull/65/files#diff-65a32a71a505e06f0e0dfb7da1071c47R58) is used in the factory.

**Actual behavior:**
`foo.toString()` returns `[object Compose]`

Currently [a few places in the stores](https://github.com/maier49/store/blob/master/src/query/createQuery.ts#L71) are relying on a custom `toString` to work properly. I can understand the intention of #65/#63, however I wonder if it makes sense to have the `toString` (if defined in the prototype) override the default one defined by the library?

**Comment by kitsonk** [comment]
Good catch.  Yes, with the addition of the diagnostic information, we started skipping that property, because it shouldn't be mixed, but of course if it is part of the provided prototype, it should be.  I agree, we should allow it to be mixed in, if it is explicitly passed.  I think we will have to modify the mixin process to allow the calling APIs to specify if the method should be overwritten or not.
